# Establece la imagen base
FROM mcr.microsoft.com/dotnet/sdk:latest AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el proyecto ASP.NET al directorio de trabajo
COPY . .

# Restaura las dependencias y compila la aplicación
RUN dotnet restore
RUN dotnet build -c Release -o /app/build

# Publica la aplicación
RUN dotnet publish -c Release -o /app/publish

# Establece la imagen base para la ejecución
FROM mcr.microsoft.com/dotnet/aspnet:latest
WORKDIR /app
COPY --from=build /app/publish .

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 80

# Comando para iniciar la aplicación al iniciar el contenedor
ENTRYPOINT ["dotnet", "WAControlServicioSocial.dll"]
